apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home"]
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      - name: docker-cli-install
        image: docker:dind
        command: ["/bin/sh", "-c"]
        args:
          - |
            DOCKER_CLI_VERSION=$(docker --version | cut -d ' ' -f 3 | cut -d ',' -f 1)
            wget -q https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_CLI_VERSION}.tgz -O /tmp/docker.tgz
            tar -xzf /tmp/docker.tgz -C /tmp
            mv /tmp/docker/docker /docker-cli/
            chmod +x /docker-cli/docker
        volumeMounts:
        - name: docker-cli
          mountPath: /docker-cli
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        command: ["/bin/sh", "-c"]
        args:
          - |
            cp /docker-cli/docker /usr/local/bin/
            DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)
            groupadd -g ${DOCKER_GID} docker
            usermod -aG docker jenkins
            chown root:docker /var/run/docker.sock
            chmod 660 /var/run/docker.sock
            su jenkins -c "/usr/local/bin/jenkins.sh"
        ports:
        - containerPort: 8080
        - containerPort: 50000
        securityContext:
          runAsUser: 0  # 초기 설정을 위해 root로 시작, 그 후 jenkins 사용자로 전환
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - name: docker-cli
          mountPath: /docker-cli
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: docker-cli
        emptyDir: {}