apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "inhochart.fullname" . }}
  namespace: {{ .Values.namespace }}  # values 파일에서 네임스페이스 값을 가져옴
  labels:
    {{- include "inhochart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | default "nginx" }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "inhochart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
