apiVersion: v1
kind: Service
metadata:
  name: {{ include "inhochart.fullname" . }}
  labels:
    {{- include "inhochart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports[0].port }}   # 포트 참조 수정
      targetPort: {{ .Values.service.ports[0].targetPort }}  # 정확히 ports[0]로 참조
      nodePort: {{ .Values.service.ports[0].nodePort | default "" }}  # NodePort 타입이 맞는지 확인
  selector:
    {{- include "inhochart.selectorLabels" . | nindent 4 }}
