apiVersion: v1
kind: Service
metadata:
  name: {{ include "inhochart.fullname" . }}
  labels:
    {{- include "inhochart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: 30996
  selector:
    {{- include "inhochart.selectorLabels" . | nindent 4 }}
