apiVersion: v1
kind: Service
metadata:
  name: {{ include "inhochart.fullname" . }}
  labels:
    {{- include "inhochart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports[0].port }}   # 배열의 첫 번째 값이 올바르게 참조되는지 확인
      targetPort: {{ .Values.service.ports[0].targetPort }}  
      nodePort: {{ .Values.service.ports[0].nodePort | default "" }} 
  selector:
    {{- include "inhochart.selectorLabels" . | nindent 4 }}
